using System.Globalization;
using System.Text.RegularExpressions;

namespace UvexAdv.Nina.Plugin;

/// <summary>
/// English counterparts for operator-facing literals kept in Templates.xaml.
/// Chinese remains the authoring language so the safety wording has one source
/// of truth; this catalog only changes presentation and never machine values.
/// </summary>
internal static partial class ObservationStaticTextCatalog
{
    private static readonly IReadOnlyDictionary<string, string> English =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["当前需要处理：{0}"] = "Needs attention: {0}",
            ["当前操作：{0}"] = "Current operation: {0}",
            ["当前影响"] = "Current impact",
            ["自动处理"] = "Automatic handling",
            ["质量数值"] = "Quality values",
            ["建议操作"] = "Recommended action",
            ["技术详情（原始消息）"] = "Technical details (raw message)",
            ["运行准入与数据归档"] = "Run admission and data archiving",
            ["目标获取、入缝与导星"] = "Target acquisition, slit placement and guiding",
            ["并行观测与站点"] = "Parallel observing and site",
            ["设备身份与标定证据"] = "Device identity and calibration evidence",
            ["目标获取算法与恢复预算（工程参数）"] = "Target-acquisition algorithms and recovery budgets (engineering)",
            ["设备身份、哈希与路径（工程核对）"] = "Device identity, hashes and paths (engineering verification)",
            ["本次界面操作未完成"] = "The requested UI operation did not complete",
            ["总体进度：{0:0}%"] = "Overall progress: {0:0}%",
            ["诊断与证据"] = "Diagnostics and evidence",
            ["当前问题"] = "Current issue",
            ["按当前预览直方图自动设置显示黑白点；只影响屏幕显示，不修改 FITS、解算或质量数据"] = "Set display black/white points from the current preview histogram; this affects only the screen and never modifies FITS, solve or quality data",
            ["按一比一显示图像"] = "Show image at 1:1",
            ["白"] = "White",
            ["弹出当前大图"] = "Open current image in a separate window",
            ["当前缩放比例"] = "Current zoom ratio",
            ["放大"] = "Zoom in",
            ["放大图像"] = "Zoom in on image",
            ["滚轮缩放 · 左键拖动 · 双击适配"] = "Mouse wheel zoom · left-drag pan · double-click to fit",
            ["黑"] = "Black",
            ["恢复 N.I.N.A. 或采集服务提供的原始预览显示"] = "Restore the original preview supplied by N.I.N.A. or the acquisition service",
            ["恢复原始预览显示"] = "Restore original preview display",
            ["切换自动拉伸"] = "Toggle automatic stretch",
            ["使完整图像适配窗口"] = "Fit the complete image to the window",
            ["适配"] = "Fit",
            ["缩小"] = "Zoom out",
            ["缩小图像"] = "Zoom out from image",
            ["完整图像适配当前视口；也可在图像上双击"] = "Fit the complete image to the current viewport; you can also double-click the image",
            ["显示：原图"] = "Display: original",
            ["一个源图像像素对应一个视图单位"] = "One source-image pixel per view unit",
            ["原图"] = "Original",
            ["在独立可缩放窗口中打开当前图像"] = "Open the current image in an independent zoomable window",
            ["自动拉伸：关"] = "Auto stretch: off",
            ["鬼影辅助模式"] = "Ghost-assistance mode",
            ["使用构图中心"] = "Use framing centre",
            ["✓ 当前没有错误或待处理证据门"] = "✓ No errors or pending evidence gates",
            ["0 = 仅记录，不阻断"] = "0 = record only; do not block",
            ["1. 观测目标"] = "1. Observation target",
            ["2. 设备身份"] = "2. Device identity",
            ["3. 一次性安装标定"] = "3. One-time installation calibration",
            ["4. 本次观测配置"] = "4. Observation configuration",
            ["5. 目标狭缝"] = "5. Target slit",
            ["6. 自动检查结果"] = "6. Automatic validation results",
            ["安全能力"] = "Safety capabilities",
            ["按钮按机械槽位编号；括号内是标称宽度。每次动作完成后必须回读到相同槽位。"] = "Buttons use mechanical slot numbers; parentheses show nominal width. Every move must read back the same slot.",
            ["绑定当前 ATR585M"] = "Bind current ATR585M",
            ["饱和核最多像素"] = "Maximum saturated-core pixels",
            ["饱和核最少像素"] = "Minimum saturated-core pixels",
            ["饱和邻星排除半径 (px)"] = "Saturated-neighbor exclusion radius (px)",
            ["保持当前位置（默认，不移动 M2）"] = "Keep current position (default; do not move M2)",
            ["保存当前高级设置"] = "Save current advanced settings",
            ["本轮显式允许 DegradedSupervised 短时有监督科学块"] = "Explicitly allow a short supervised DegradedSupervised science block for this run",
            ["本夜 M2 策略"] = "Tonight's M2 policy",
            ["本夜光学设置 ID"] = "Night optical-setup ID",
            ["本夜光学设置 SHA-256"] = "Night optical-setup SHA-256",
            ["本夜光学设置快照文件"] = "Night optical-setup snapshot file",
            ["边缘安全距离 (px)"] = "Edge safety margin (px)",
            ["编辑观测计划"] = "Edit observation plan",
            ["标定包静态校验已通过（最新完整包默认自动确认；不会绕过运行时硬门）"] = "Calibration package passed static validation (the newest complete package is confirmed by default; runtime hard gates remain enforced)",
            ["并行观测与初始地平线规划时长（分钟）"] = "Parallel-observation and initial-horizon planning duration (minutes)",
            ["波长(nm)"] = "Wavelength (nm)",
            ["波长标定参考"] = "Wavelength-calibration reference",
            ["不确定度上限 (arcsec)"] = "Maximum uncertainty (arcsec)",
            ["步"] = "steps",
            ["步长 (arcsec)"] = "Step size (arcsec)",
            ["采集计划"] = "Acquisition plan",
            ["采集一帧检查光谱"] = "Capture one spectrum for inspection",
            ["参考谱线当前位置（1D 光谱 px）"] = "Current reference-line position (1D spectrum px)",
            ["参考谱线目标位置（1D 光谱 px）"] = "Target reference-line position (1D spectrum px)",
            ["参考谱线位置（1D 光谱 px）"] = "Reference-line positions (1D spectrum px)",
            ["测光相机 QHY"] = "QHY photometry camera",
            ["测量曝光（秒）"] = "Measurement exposure (seconds)",
            ["查看工程诊断"] = "View engineering diagnostics",
            ["超亮目标：饱和核的未饱和翼部入缝（例外分支，默认关闭）"] = "Very bright target: place unsaturated wings around a saturated core on the slit (exception path; off by default)",
            ["超时(s)"] = "Timeout (s)",
            ["撤销本次模板修改"] = "Undo this template change",
            ["赤道仪 DeviceId"] = "Mount DeviceId",
            ["赤道仪（N.I.N.A.）"] = "Mount (N.I.N.A.)",
            ["赤经 RA（J2000，度）"] = "Right ascension RA (J2000, degrees)",
            ["赤纬 Dec（J2000，度）"] = "Declination Dec (J2000, degrees)",
            ["垂直色散（沿 Y）"] = "Vertical dispersion (along Y)",
            ["此序列请求 REAL 模式"] = "This sequence requests REAL mode",
            ["次峰/鬼影比例上限"] = "Maximum secondary-peak/ghost ratio",
            ["从第三方星图当前选择导入"] = "Import current selection from third-party atlas",
            ["从构图助手当前构图导入"] = "Import current framing from Framing Assistant",
            ["错误 / 阻断"] = "Error / blocked",
            ["打开草稿位置"] = "Open draft location",
            ["打开目录"] = "Open folder",
            ["打开失败证据目录"] = "Open failure-evidence folder",
            ["打开照明灯"] = "Turn slit light on",
            ["打开最近证据目录"] = "Open latest-evidence folder",
            ["大步后允许拍 fresh 验证帧的最大实报终点残差 (arcsec)"] = "Maximum reported endpoint residual that permits a fresh verification frame after a large move (arcsec)",
            ["单次上限 (arcsec)"] = "Per-action limit (arcsec)",
            ["单动作最坏时长 (s)"] = "Worst-case action duration (s)",
            ["单独授权 UVEX 光栅波长锁定（会产生光栅机械运动）"] = "Separately authorize UVEX grating wavelength lock (moves the grating)",
            ["单样本永远是 Candidate；需独立聚合/验证后才能激活。"] = "A single sample always remains Candidate; independent aggregation and validation are required before activation.",
            ["单张 QHY 曝光 (s)"] = "QHY exposure per frame (s)",
            ["弹出 ATR 大图"] = "Open large ATR view",
            ["弹出 G3 大图"] = "Open large G3 view",
            ["弹出 QHY 大图"] = "Open large QHY view",
            ["当前 Profile 模板"] = "Current Profile template",
            ["当前："] = "Current: ",
            ["当前有界动作结束后阻止下一项动作或曝光。"] = "Prevent the next action or exposure after the current bounded action finishes.",
            ["导入设备标定方案"] = "Import device-calibration profile",
            ["导入锁定本夜配置"] = "Import and lock tonight's configuration",
            ["导入完整标定包"] = "Import complete calibration package",
            ["导星相机 G3 / PHD2"] = "Guide camera G3 / PHD2",
            ["灯状态是服务命令完成回读；UVEX 串口协议不提供独立电气遥测。"] = "The light state is command-completion readback from the service; the UVEX serial protocol has no separate electrical telemetry.",
            ["动作"] = "Action",
            ["断开"] = "Disconnect",
            ["对向翼部平衡下限"] = "Minimum opposed-wing balance",
            ["范围与连接"] = "Scope and connection",
            ["分钟"] = "minutes",
            ["高级设置"] = "Advanced settings",
            ["高级设置保存"] = "Advanced-settings save",
            ["关闭照明灯"] = "Turn slit light off",
            ["观测计划"] = "Observation plan",
            ["光谱相机 ATR"] = "ATR spectroscopy camera",
            ["光栅锁定"] = "Grating lock",
            ["光栅响应（带符号的电机步 / px）"] = "Grating response (signed motor steps / px)",
            ["广域→狭缝场转换"] = "Wide-field → slit-field transform",
            ["海拔（米）"] = "Elevation (m)",
            ["候选有效期 (h)"] = "Candidate lifetime (h)",
            ["缓存最长年龄 (s)"] = "Maximum cache age (s)",
            ["恢复复核"] = "Resume with revalidation",
            ["恢复前重新检查全部可能过期的门。"] = "Recheck every potentially stale gate before resuming.",
            ["继续裕量"] = "Continue margin",
            ["继续运行裕量（度）"] = "Continue-running margin (degrees)",
            ["加载所选方案"] = "Load selected profile",
            ["兼容性键（不同参数绝不混库）"] = "Compatibility key (never mix differing parameters)",
            ["交叉色散孔径起点 / 长度（px）"] = "Cross-dispersion aperture start / length (px)",
            ["角向覆盖下限"] = "Minimum angular coverage",
            ["接缝门（σ）"] = "Seam gate (σ)",
            ["解算曝光档位 (ms)"] = "Plate-solve exposure tiers (ms)",
            ["仅提供辅助质心与协方差，不授予目标身份或运动权限。"] = "Provides only an assisting centroid and covariance; it grants neither target identity nor motion authority.",
            ["进入维护模式（取消为退出）"] = "Enter maintenance mode (clear to exit)",
            ["旧版 QHY 广域运动门（仅保留兼容/取证，不是当前生产路线）"] = "Legacy QHY wide-field motion gates (retained only for compatibility/evidence; not the current production route)",
            ["开始建立/补充校准库"] = "Start building / extending calibration library",
            ["库目录"] = "Library folder",
            ["宽 / 高（px）"] = "Width / height (px)",
            ["累计含回程 (arcsec)"] = "Cumulative including return (arcsec)",
            ["累计运动 (arcsec)"] = "Cumulative motion (arcsec)",
            ["连接"] = "Connect",
            ["连续全幅之间；本机实测 3000 ms"] = "Between consecutive full frames; 3000 ms measured on this system",
            ["两帧中点差 (s)"] = "Frame-midpoint separation (s)",
            ["留空沿用单滤镜测光；行星状星云示例：H:60,O:60,S:60"] = "Leave blank for single-filter photometry; planetary-nebula example: H:60,O:60,S:60",
            ["滤镜循环（Filter:秒，逗号分隔）"] = "Filter cycle (Filter:seconds, comma-separated)",
            ["每次"] = "Each move",
            ["每档张数"] = "Frames per tier",
            ["模拟"] = "Simulation",
            ["模拟时每阶段停留时间（毫秒）"] = "Per-stage delay in simulation (ms)",
            ["模拟自动观测；只切换模式，不会连接或移动设备。"] = "Simulated automatic observation; this only changes mode and neither connects nor moves equipment.",
            ["模式"] = "Mode",
            ["目标"] = "Target",
            ["目标波段"] = "Target band",
            ["目标导入"] = "Target import",
            ["目标定位辅助"] = "Target-location assistance",
            ["目标画内边距 (px)"] = "Target frame margin (px)",
            ["目标类型"] = "Target type",
            ["目标名称"] = "Target name",
            ["目标温度 °C"] = "Target temperature °C",
            ["目标在 G3 中的可观测类型"] = "Target observability class in G3",
            ["目录 ID"] = "Catalog ID",
            ["目录坐标差上限 (arcsec)"] = "Maximum catalog-coordinate mismatch (arcsec)",
            ["内外质心差上限 (px)"] = "Maximum inner/outer centroid disagreement (px)",
            ["配对 schema"] = "Pairing schema",
            ["曝光 preset ID"] = "Exposure preset ID",
            ["曝光 preset schema"] = "Exposure preset schema",
            ["七点扫描步长（M2 电机步）"] = "Seven-point scan spacing (M2 motor steps)",
            ["启动"] = "Start",
            ["启动丢弃帧"] = "Startup discard frames",
            ["启动裕量"] = "Start margin",
            ["启动裕量（度）"] = "Start margin (degrees)",
            ["启用 ATR585M SDK 行回绕自动修复"] = "Enable automatic ATR585M SDK row-wrap repair",
            ["启用并核验恒星时跟踪"] = "Enable and verify sidereal tracking",
            ["切换狭缝"] = "Select slit",
            ["清除 G3 状态"] = "Clear G3 state",
            ["取消并收尾"] = "Cancel and finalize",
            ["取消当前运行并执行安全收尾。"] = "Cancel the current run and perform safe finalization.",
            ["确定性鬼影辅助"] = "Deterministic ghost assistance",
            ["确定性鬼影辅助（受设备标定约束）"] = "Deterministic ghost assistance (constrained by device calibration)",
            ["人工接管"] = "Manual takeover",
            ["软件提取矩形（原始全帧像素）"] = "Software extraction rectangle (original full-frame pixels)",
            ["色散方向"] = "Dispersion direction",
            ["尚无 G3 狭缝场图像"] = "No G3 slit-field image yet",
            ["尚无 QHY 广域图像"] = "No QHY wide-field image yet",
            ["尚无自动观测 ATR 图像"] = "No automatic-observation ATR image yet",
            ["设备"] = "Device",
            ["设备标定方案 ID"] = "Device-calibration profile ID",
            ["设备标定方案 SHA-256"] = "Device-calibration profile SHA-256",
            ["设备标定文件"] = "Device-calibration file",
            ["设备手控"] = "Device controls",
            ["设备所有权预检"] = "Device-ownership preflight",
            ["失败诊断"] = "Failure diagnostics",
            ["时间线"] = "Timeline",
            ["实时图像"] = "Live images",
            ["使用当前构图中心"] = "Use current framing center",
            ["释放 COM5 给原厂软件"] = "Release COM5 to vendor software",
            ["刷新相机状态"] = "Refresh camera status",
            ["刷新状态"] = "Refresh status",
            ["水平色散（沿 X）"] = "Horizontal dispersion (along X)",
            ["搜索尝试次数"] = "Search attempts",
            ["台站配置方案"] = "Observatory configuration profile",
            ["填写自动准备表单"] = "Complete automatic-preparation form",
            ["同向逼近预压量（M2 电机步）"] = "Same-direction approach preload (M2 motor steps)",
            ["完成当前操作后取消"] = "Cancel after current operation",
            ["围墙"] = "Wall",
            ["围墙最低高度角（度）"] = "Wall minimum altitude (degrees)",
            ["唯一性比值下限"] = "Minimum uniqueness ratio",
            ["位移（px）"] = "Shift (px)",
            ["温度容差 ±°C"] = "Temperature tolerance ±°C",
            ["我确认：镜头盖已盖好，屋顶已关闭，设备内没有漏光"] = "I confirm: the lens cap is on, the roof is closed, and no light is leaking into the instrument",
            ["无人值守自动推进；失败自动暂停，支持恢复、取消与人工接管。"] = "Unattended automatic progression; failures pause automatically, with resume, cancel, and manual takeover available.",
            ["狭缝"] = "Slit",
            ["狭缝轮光学身份复核"] = "Slit-wheel optical identity verification",
            ["狭缝照明灯"] = "Slit illumination",
            ["下一步："] = "Next: ",
            ["显式启用超亮目标翼部质心分支"] = "Explicitly enable the very-bright-target wing-centroid path",
            ["相对步数"] = "Relative steps",
            ["详细策略"] = "Detailed policy",
            ["新开一轮"] = "Start a new run",
            ["选择/导入目标"] = "Select / import target",
            ["移动后稳定等待 (s)"] = "Post-move settle wait (s)",
            ["已安装并经过确认的级次分选滤镜"] = "Installed and verified order-sorting filter",
            ["已绑定 ATR DeviceId"] = "Bound ATR DeviceId",
            ["已保存；打开本页不会连接"] = "Saved; opening this page does not connect",
            ["已标定的七点谱线自动对焦（会移动 M2）"] = "Commissioned seven-point spectral autofocus (moves M2)",
            ["翼部 ADU 上限/饱和"] = "Maximum wing ADU / saturation",
            ["翼部 SNR 下限"] = "Minimum wing SNR",
            ["翼部半径 (px)"] = "Wing radius (px)",
            ["翼部显著性下限 (sigma)"] = "Minimum wing prominence (sigma)",
            ["翼部最少像素"] = "Minimum wing pixels",
            ["应用推荐的目标分目录模板"] = "Apply recommended target subfolder template",
            ["英文逗号分隔，例如 300,600"] = "Comma-separated, for example 300,600",
            ["硬件指纹 SHA-256"] = "Hardware fingerprint SHA-256",
            ["允许的绝对最大位置（M2 步）"] = "Maximum permitted absolute position (M2 steps)",
            ["允许的绝对最小位置（M2 步）"] = "Minimum permitted absolute position (M2 steps)",
            ["运行概览"] = "Overview",
            ["暂停"] = "Pause",
            ["增益（-1 表示不覆盖）"] = "Gain (-1 means do not override)",
            ["站点、40° 围墙与模拟速度"] = "Site, 40° wall, and simulation speed",
            ["站点东经（度）"] = "Site longitude east (degrees)",
            ["站点纬度（度）"] = "Site latitude (degrees)",
            ["长波二级谱抑制"] = "Long-wavelength second-order suppression",
            ["真实"] = "Real",
            ["真实模式启动条件"] = "Real-mode startup requirements",
            ["真实自动观测；只选择执行方式，不是设备连接按钮。"] = "Real automatic observation; this selects execution mode and is not a device-connect button.",
            ["真实自动观测准备表"] = "Real automatic-observation preparation",
            ["整组时限 (s)"] = "Group time limit (s)",
            ["正在读取目标并换算 J2000 坐标……"] = "Reading target and converting to J2000 coordinates…",
            ["证据文件"] = "Evidence file",
            ["质量门"] = "Quality gate",
            ["质量门与证据"] = "Quality gates and evidence",
            ["重新读取 N.I.N.A. 设备选择"] = "Reload N.I.N.A. device selections",
            ["重新扫描"] = "Rescan",
            ["重新扫描保存的配置"] = "Rescan saved configurations",
            ["注册表赤道仪名"] = "Registry mount name",
            ["注册表相机名"] = "Registry camera name",
            ["自动流程（真实成功路线）"] = "Automatic workflow (successful real route)",
            ["自动生成准备草稿"] = "Generate preparation draft automatically",
            ["自动准备"] = "Automatic preparation",
            ["总动作次数"] = "Total actions",
            ["最大半径 (arcsec)"] = "Maximum radius (arcsec)",
            ["最大饱和比例"] = "Maximum saturation fraction",
            ["最低透明度"] = "Minimum transparency",
            ["最短 G3 曝光 (ms)"] = "Minimum G3 exposure (ms)",
            ["最少星数"] = "Minimum star count",
            ["最长粗居中 (min)"] = "Maximum coarse-centering time (min)",
            ["最长搜索 (min)"] = "Maximum search time (min)",
            ["左上角 X / Y（px）"] = "Top-left X / Y (px)",
            ["ATR 单帧检查"] = "ATR single-frame inspection",
            ["ATR 二维 / 一维光谱"] = "ATR 2D / 1D spectrum",
            ["ATR 提取"] = "ATR extraction",
            ["ATR 型号名回退（仅影子检查）"] = "ATR model-name fallback (shadow check only)",
            ["ATR 长曝光期间的 QHY 并行成像"] = "Parallel QHY imaging during long ATR exposures",
            ["ATR585M 校准库"] = "ATR585M calibration library",
            ["Bias 曝光(s)"] = "Bias exposure (s)",
            ["Bias 张数"] = "Bias frame count",
            ["C11 焦点置信度下限"] = "Minimum C11 focus confidence",
            ["Dark 曝光(s)"] = "Dark exposure (s)",
            ["G3 对焦 / 狭缝 / 导星"] = "G3 focus / slit / guiding",
            ["G3 曝光 (ms)"] = "G3 exposure (ms)",
            ["G3 驱动恢复 (ms)"] = "G3 driver recovery (ms)",
            ["G3 相对天空提示可信范围 (deg)"] = "Trusted G3 sky-hint range (deg)",
            ["G3 一旦解算成功，立即建立 QHY/G3 快速双解算候选"] = "Create a fast QHY/G3 dual-solve candidate as soon as G3 solves",
            ["G3 增益 (%)"] = "G3 gain (%)",
            ["G3 长曝光解算与 WCS 居中"] = "G3 long-exposure solve and WCS centering",
            ["G3 帧最长年龄 (min)"] = "Maximum G3 frame age (min)",
            ["G3 直接解算失败后的有界方形螺旋搜索"] = "Bounded square-spiral search after direct G3 solve failure",
            ["JSON-RPC 运行时赤道仪名"] = "JSON-RPC runtime mount name",
            ["JSON-RPC 运行时相机名"] = "JSON-RPC runtime camera name",
            ["M2 对焦"] = "M2 focus",
            ["M2 简单对焦"] = "Simple M2 focus",
            ["N.I.N.A. 原生目标归档"] = "N.I.N.A. native target archive",
            ["OpenAstroSpec 推荐模板"] = "OpenAstroSpec recommended template",
            ["OpenAstroSpec Auto · ATR/UVEX4 光谱工具设置"] = "OpenAstroSpec Auto · ATR/UVEX4 spectroscopy tool settings",
            ["PHD2 导星"] = "PHD2 guiding",
            ["PHD2 名称分域（必须精确匹配，不做模糊匹配）"] = "PHD2 name domains (exact match required; no fuzzy matching)",
            ["PHD2 校准质量"] = "PHD2 calibration quality",
            ["PHD2 与目标定位策略详情"] = "PHD2 and target-location policy details",
            ["QHY 广域 / 解算"] = "QHY wide field / solving",
            ["QHY 目标残差上限 (arcsec)"] = "Maximum QHY target residual (arcsec)",
            ["QHY WCS 最长年龄 (min)"] = "Maximum QHY WCS age (min)",
            ["UVEX 服务 API 地址"] = "UVEX service API address",
            ["UVEX4 手动准备"] = "UVEX4 manual preparation",
            ["WCS 门 schema"] = "WCS gate schema",

            // Explanatory text and safety tooltips. These remain exact entries so
            // a translation can never accidentally weaken one clause by applying
            // a broad word replacement.
            ["10/20 ms HDR 测量黑色暗孔径的两条物理边；强反光允许过曝，其 FWHM 不再当作缝宽。四槽位必须分别实测；不唯一、超出指纹族或与回报序号不符时，任何入缝与科学曝光都会在运动前阻断。"] = "10/20 ms HDR measures the two physical edges of the dark aperture. Specular reflections may saturate and their FWHM is not treated as slit width. All four slots must be measured separately; non-unique geometry, a fingerprint-family mismatch, or a reported-slot mismatch blocks slit placement and science before motion.",
            ["按当前设置新开一轮。用于切换超亮目标等会改变动作哈希的分支：先结束旧运行并审计退役旧 G3 恢复链，再按当前表单捕获新哈希并启动。不会把新设置热替换进旧运行，也不要求把设置改回去。"] = "Start a new run with the current settings. Use this for branches such as very-bright targets that change the action hash: finish the old run, audit and retire its G3 recovery chain, then capture a new hash from the current form and start. Settings are never hot-swapped into an old run, and you do not have to revert the form.",
            ["不是曝光倒计时：已开始的 ATR 曝光会完整结束；ATR 科学帧张数由高级设置控制。600 s 单帧不会在这里填 10 分钟时被中途截断。"] = "This is not an exposure countdown: an ATR exposure already in progress completes in full, and the ATR science-frame count is controlled in Advanced settings. A 600 s frame is not cut short when this field is set to 10 minutes.",
            ["草稿会自动汇总保存的身份、相机参数、狭缝和上述选择，但不会连接设备，也不会把尚未实测的焦点、光栅或运动证据伪装成已完成。"] = "The draft summarizes saved identities, camera parameters, slit, and the selections above. It does not connect equipment or present unmeasured focus, grating, or motion evidence as complete.",
            ["从 N.I.N.A. 构图或第三方星图读取目标草稿；只更新目标字段，不连接设备或启动观测。"] = "Read a target draft from N.I.N.A. framing or a third-party atlas. This only updates target fields; it does not connect equipment or start observing.",
            ["读取本次构图矩形的初始中心或当前构图中心并换算为 J2000 坐标；不会操作设备。"] = "Read the initial or current center of this framing rectangle and convert it to J2000 coordinates; equipment is not operated.",
            ["当前前端只接受 QHY 正式 WCS 作为广域见证，不依据它移动赤道仪；大步运动交给 fresh G3 WCS + N.I.N.A.。以下 schema 1 参数只供旧运行记录重放和工程诊断，不再作为当前路线的启动阻断项。"] = "The current frontend accepts formal QHY WCS only as wide-field evidence and does not move the mount from it; large moves use fresh G3 WCS plus N.I.N.A. The schema 1 parameters below are retained only for legacy-run replay and engineering diagnostics and no longer block startup on the current route.",
            ["导入不会改变本夜光学设置、设备标定、安全限制、运行模式或已创建的高级序列；入缝前仍需复核目录身份与 J2000 坐标。站点、地平线和模拟速度已移到“高级设置”。"] = "Import does not change tonight's optical setup, device calibration, safety limits, execution mode, or existing Advanced Sequences. Catalog identity and J2000 coordinates must still be verified before slit placement. Site, horizon, and simulation speed are under Advanced settings.",
            ["设备所有权：N.I.N.A. 独占 ATR585M；UvexAdv.Service 独占 UVEX4 / COM5。此页不会让插件直接打开相机 SDK 或串口。"] = "Device ownership: N.I.N.A. exclusively owns ATR585M; UvexAdv.Service exclusively owns UVEX4 / COM5. This page never lets the plugin open the camera SDK or serial port directly.",
            ["光栅闭环测量一条已知参考谱线，把它移动到指定的 1D 光谱像素。步/像素必须带正确正负方向；这不是名义波长输入，也不等同于自动观测已调试。"] = "The grating closed loop measures a known reference line and moves it to a specified 1D-spectrum pixel. Steps per pixel must have the correct sign; this is not a nominal-wavelength input and does not mean automatic observing is commissioned.",
            ["关闭 COM5 并保持断开；服务不会在后台自动重连。"] = "Close COM5 and remain disconnected; the service does not reconnect in the background.",
            ["空白表示尚未配置。界面不再显示内部 NaN 哨兵值；任何字段缺失或响应为 0 时，闭环会在申请 UVEX 控制租约之前拒绝。"] = "Blank means not configured. The UI no longer exposes the internal NaN sentinel; if any field is missing or the response is zero, the closed loop refuses before requesting the UVEX control lease.",
            ["孔径起点是相对于上述软件提取矩形、沿交叉色散方向的偏移；它不是整幅图像坐标。"] = "Aperture start is an offset within the software extraction rectangle above, along the cross-dispersion direction; it is not a full-frame coordinate.",
            ["连接相机后的前几帧不入库，用于稳定 ToupTek 读出链路"] = "Discard the first frames after camera connection to stabilize the ToupTek readout path",
            ["默认 5°；优先相对新鲜 QHY/PL3 WCS 检验，并作为无机械零位赤道仪的一次性 Sync 触发阈值。不会自动扩大此值，也不授权同等幅度 Slew"] = "Default 5°. Prefer validation against fresh QHY/PL3 WCS; for a mount without a mechanical home, this is the threshold for a one-time Sync. It is never expanded automatically and does not authorize a Slew of the same size.",
            ["默认关闭。只有当前锁定动作配置勾选后，有监督降级模式才可继续；它仍不获得无人值守权限，所有后续证据/帧必须标注降级。设备标定方案不能替你勾选。"] = "Off by default. Supervised degraded mode can continue only when explicitly enabled in the current locked action configuration. It never gains unattended authority, and all subsequent evidence and frames must be marked degraded. A device-calibration profile cannot enable it for you.",
            ["默认关闭并使用构图矩形的初始中心；打开后使用当前画面中心。"] = "Off by default, using the framing rectangle's initial center; turn on to use the current view center.",
            ["目录转向 → QHY 广域见证 → G3 解算 / N.I.N.A. 大步修正 / 邻场搜索 → PHD2 入缝并导星 → ATR 自适应曝光 + QHY 同步测光"] = "Catalog slew → QHY wide-field evidence → G3 solve / N.I.N.A. large correction / nearby-field search → PHD2 slit placement and guiding → ATR adaptive exposure + synchronized QHY photometry",
            ["判据分离：2″只约束静态 frame/mount 绑定和小步搜索稳定性；大步实报终点在完整运动预算内即可拍验证帧，光学到位必须由移动后的 fresh G3 WCS 证明。"] = "Separate criteria: 2″ constrains only static frame/mount binding and small-step search stability. A reported endpoint after a large move may take a verification frame when within the full motion budget; optical arrival must be proven by fresh post-move G3 WCS.",
            ["曝光由 N.I.N.A. 执行；插件不会直接加载 ToupTek SDK，也不会打开导星相机。"] = "Exposures are executed by N.I.N.A.; the plugin neither loads the ToupTek SDK directly nor opens the guide camera.",
            ["启动时默认选择最新完整标定包；哈希、内部引用和设备身份的静态校验全部通过后自动确认。此过程不连接或移动设备。"] = "At startup the newest complete calibration package is selected by default and confirmed after its hash, internal references, and device identity all pass static validation. This neither connects nor moves equipment.",
            ["启动时自动恢复上次台站方案；设备候选来自 N.I.N.A.、PHD2 和 QHY 服务各自保存的配置。列出候选不会连接设备，红框只表示真正缺少的资料。"] = "The last observatory profile is restored at startup. Device candidates come from configurations saved independently by N.I.N.A., PHD2, and the QHY service. Listing candidates does not connect equipment; red borders indicate genuinely missing information only.",
            ["启用前必须填写最短曝光、证据新鲜度和 QHY 残差；0 表示未配置并阻断。这里没有目标名、目标坐标、两镜光轴偏移或固定 500 ms。"] = "Before enabling, enter the minimum exposure, evidence freshness, and QHY residual. Zero means unconfigured and blocks this path. No target name, target coordinates, fixed inter-camera axis offset, or fixed 500 ms value is stored here.",
            ["清除旧 G3 状态：取消当前失败运行，接受人工接管后的当前状态并关闭过时的 G3 自动返回账本。不会移动赤道仪；原账本与审计记录会保留。清除后可直接重新启动。"] = "Clear old G3 state: cancel the failed run, accept the current state after manual takeover, and close the stale G3 automatic-return ledger. This does not move the mount; the original ledger and audit record are retained. You may start again immediately afterward.",
            ["让服务进入维护模式并关闭 COM5；不会移动任何机构。再次点击连接 UVEX4 可恢复。"] = "Put the service into maintenance mode and close COM5 without moving any mechanism. Click Connect UVEX4 again to restore service.",
            ["尚未收到 PHD2/G3 全帧。请检查当前阶段和最近质量门；G3 仍只由 PHD2 持有。"] = "No PHD2/G3 full frame has been received. Check the current stage and latest quality gate; G3 remains exclusively owned by PHD2.",
            ["尚未收到 QHY/GS350 取景帧。请查看固定运行状态、QHY 当前阶段和最近质量门；选择模式本身不会连接相机。"] = "No QHY/GS350 preview frame has been received. Check locked-run status, the current QHY stage, and the latest quality gate; selecting a mode does not connect the camera.",
            ["输入框、下拉框和复选框会立即更新当前 N.I.N.A. Profile 的内存设置；点击下方按钮可立即写盘，不必依赖关闭 N.I.N.A. 时保存。已经开始的运行仍使用其启动时锁定的快照。"] = "Text fields, lists, and check boxes immediately update the current N.I.N.A. Profile in memory. Use the button below to save immediately instead of relying on N.I.N.A. shutdown. A run already started continues to use its startup-locked snapshot.",
            ["它与 ATR 光谱曝光并行，不借用 ATR 或 G3 相机；若 QHY 支路被设为严格质量门，失败仍会暂停主流程。"] = "This runs in parallel with ATR spectral exposures and borrows neither the ATR nor G3 camera. If the QHY branch is configured as a strict quality gate, its failure still pauses the main workflow.",
            ["通过 N.I.N.A. 当前第三方星图设置读取已选目标；不会操作设备。"] = "Read the selected target from N.I.N.A.'s current third-party atlas settings; equipment is not operated.",
            ["显式打开已保存的 UVEX4 / COM5 并读取可信位置。"] = "Explicitly open the saved UVEX4 / COM5 connection and read a trusted position.",
            ["选择保存在当前 N.I.N.A. Profile；本机安全配置只允许 UVEX4 / COM5，不扫描其他串口。"] = "The selection is saved in the current N.I.N.A. Profile. This system's safety configuration permits only UVEX4 / COM5 and never scans other serial ports.",
            ["样本达到 5 张且质量门通过时生成剔除一高一低像素的 master（Master Dark 保留 bias）"] = "When at least 5 samples pass quality gates, build a master with one high and one low pixel rejected (Master Dark retains bias)",
            ["用于绑定相机和检查提取结果；不会启动入缝、导星、UVEX 运动或自动科学序列。"] = "Used to bind the camera and inspect extraction results; it does not start slit placement, guiding, UVEX motion, or an automatic science sequence.",
            ["用于并行 QHY 任务长度及自动观测开始时的地平线保护估算；不是 ATR 单帧曝光的硬超时。"] = "Used for the parallel QHY task duration and horizon-protection estimate at observation start; it is not a hard timeout for an ATR exposure.",
            ["用于观测前借天光选缝、开关狭缝灯和简单调整 M2。只经过 UvexAdv.Service → COM5；不要求本夜光学设置、PHD2、QHY、WCS 或完整自动观测标定。"] = "Use before observing to select a slit in daylight, switch slit illumination, and make simple M2 adjustments. This goes only through UvexAdv.Service → COM5 and requires neither tonight's optical setup, PHD2, QHY, WCS, nor complete automatic-observation calibration.",
            ["由操作员选择；如果导入了本夜光学设置，会自动选中其中记录的槽位。"] = "Selected by the operator; importing tonight's optical setup automatically selects its recorded slot.",
            ["这里不是普通表单：ID、SHA-256、四槽狭缝指纹、三焦域身份和运动限额必须由标定流程整体生成或导入，界面不会让你手抄。"] = "This is not an ordinary form. IDs, SHA-256 values, four-slot slit fingerprints, three focus-domain identities, and motion limits must be generated or imported as one calibration package; the UI does not ask you to transcribe them.",
            ["这里的“对焦”只指 UVEX 光谱仪内部 M2，通过多条谱线的 FWHM 做七点扫描。它与 C11 主镜、G3M2210M 导星模组小镜头和狭缝照明图像对焦无关。"] = "Focus here means only the UVEX spectrograph's internal M2, scanned at seven points using the FWHM of multiple spectral lines. It is unrelated to C11 primary-mirror focus, the G3M2210M guide-module lens, or slit-illumination image focus.",
            ["这里只配置自动观测界面中的 ATR 单帧检查，以及 Advanced Sequencer 中的 UVEX4 M2 谱线对焦和光栅波长锁定。它不配置 C11 主镜对焦、G3 导星镜对焦、目标入缝或自动科学曝光计划。"] = "This page configures ATR single-frame inspection in the automatic-observation UI and UVEX4 M2 spectral-line focus and grating wavelength lock in Advanced Sequencer. It does not configure C11 primary-mirror focus, G3 guide-scope focus, target slit placement, or an automatic science-exposure plan.",
            ["这里只选择期望身份：ATR 仍归 N.I.N.A.，G3 仍归 PHD2，QHY 仍归独立 QHY 服务。无需把三台相机轮流接进 N.I.N.A.。"] = "This only selects expected identities: ATR remains owned by N.I.N.A., G3 by PHD2, and QHY by the independent QHY service. The three cameras do not need to be connected to N.I.N.A. in turn.",
            ["这些数值由所选台站配置方案加载，且不得超过设备标定的运动上限；0 表示未调试并会阻断真实模式。每步均重新检查暂停、安全、屋顶、天气、地平线和赤道仪状态，失败时按小步安全返回搜索原点。"] = "These values come from the selected observatory profile and must not exceed calibrated motion limits. Zero means uncommissioned and blocks real mode. Every step rechecks pause, safety, roof, weather, horizon, and mount state; failure returns safely to the search origin in small steps.",
            ["这些值只用于光谱工具的 ATR 单帧测量。所谓“提取矩形”是在 N.I.N.A. 完整图像上做的软件裁切，不会改写相机驱动的硬件 ROI。"] = "These values are used only for ATR single-frame measurements in the spectroscopy tool. The extraction rectangle is a software crop of the complete N.I.N.A. image and never changes the camera driver's hardware ROI.",
            ["这些字段用于不可变设备身份和标定来源追踪。日常操作请在“自动准备”选择台站配置方案；这里只保留工程诊断与人工核对。"] = "These fields track immutable device identity and calibration provenance. For routine operation select an observatory profile under Automatic preparation; this section is retained for engineering diagnostics and manual verification.",
            ["只适用于目标身份已由本轮新鲜 QHY WCS + 目录坐标锁定、并且 C11/Star Focuser Pro 有独立有效焦点证据的超亮目标。短曝光 G3 帧即使能用翼部求质心，也永远不能参与对焦；G3 解算失败本身不会放宽身份、唯一性或运动门。"] = "Only for a very bright target whose identity is locked by fresh QHY WCS plus catalog coordinates in this run and whose C11/Star Focuser Pro has independent valid focus evidence. Even if a short G3 frame yields a wing centroid, it can never provide focus evidence; G3 solve failure alone never relaxes identity, uniqueness, or motion gates.",
            ["只有错误或动作所需证据不足才会暂停；警告会保留在“质量门与证据”中并继续自动流程。"] = "Only an error or insufficient evidence for a required action pauses the run. Warnings remain in Quality gates and evidence while the automatic workflow continues.",
            ["只在普通/超亮目标身份定位失败时，使用同一无运动 OFF/ON/OFF 序列中至少两张新鲜、同曝光 OFF 帧。标定、完整策略、提取策略、安装/方向指纹均由 schema 4 preset 及其 SHA-256 绑定；不含目标常量或两镜固定光轴差。"] = "Only after normal and very-bright target identity location both fail, use at least two fresh equal-exposure OFF frames from the same motionless OFF/ON/OFF sequence. Calibration, full policy, extraction policy, and installation/orientation fingerprints are bound by a schema 4 preset and its SHA-256; no target constants or fixed inter-camera axis offset are included.",
            ["只做相对小步进；绝对行程和单次最大步数仍由 UVEX 服务限位。"] = "Only small relative moves are made; absolute travel and maximum steps per move remain limited by the UVEX service.",
            ["自动观测准备与 UVEX 手控彼此独立；切缝和 M2 对焦不需要先填完自动观测表单。"] = "Automatic-observation preparation and UVEX manual control are independent; selecting a slit or focusing M2 does not require completion of the automatic-observation form.",
            ["自动流程尚未收到 N.I.N.A./ATR585M 探测或科学帧。右侧单帧检查不会启动整套自动观测。"] = "The automatic workflow has not received a N.I.N.A./ATR585M acquisition or science frame. The single-frame inspection on the right does not start the full automatic observation.",
            ["ATR585M 没有机械快门。开始前必须人工确认暗环境；此确认不会写入 Profile。"] = "ATR585M has no mechanical shutter. A dark environment must be confirmed manually before starting; this confirmation is not saved to the Profile.",
            ["ATR585M 仍由 N.I.N.A. 保存。模板必须包含目标名；推荐值还会按夜晚、目标和官方图像类型分目录。插件不会在启动时静默修改 Profile。"] = "ATR585M remains saved by N.I.N.A. The template must include the target name; recommended values also create subfolders by night, target, and official image type. The plugin never silently changes the Profile at startup.",
            ["DeviceId 由“OpenAstroSpec 自动观测 → 实时图像 → ATR 二维/一维光谱”或校准库中的显式“绑定当前 ATR585M”按钮写入。绑定后闭环必须精确匹配 DeviceId；型号名称不能绕过绑定。"] = "DeviceId is written by the explicit Bind current ATR585M button under OpenAstroSpec automatic observation → Live images → ATR 2D / 1D spectrum, or in the calibration library. Once bound, the closed loop must match DeviceId exactly; a model name cannot bypass the binding.",
            ["曝光档位是带版本的设备参数；每档都由 PHD2 独占 G3 拍一张新全帧。若同一指向已有本轮新鲜 QHY/PL3 正式解，G3 优先以它作为真实天空提示；当无机械零位赤道仪的自报坐标偏差超过此处可信范围时，每轮最多用该 QHY 真值 Sync 一次并验证读回，绝不反复同步或发 Slew。G3 正式解在像元尺度合理、数值有限且位于提示可达范围内时直接信任；源数和匹配数只作遥测。目标/赤道仪与 QHY 的大残差不再误写成两镜光轴差。若目标在画外，插件按该新 WCS 经 N.I.N.A. 做有界分段居中，再用新实报位置和新 G3 解验证实际天球响应。"] = "Exposure tiers are versioned device parameters; at each tier PHD2 exclusively acquires one new G3 full frame. If this run already has a fresh formal QHY/PL3 solve at the same pointing, G3 prefers it as the true-sky hint. When a mount without mechanical home reports coordinates outside this trusted range, at most one Sync to that QHY truth is allowed per run and its readback is verified; Sync is never repeated and no Slew is implied. A formal G3 solve is trusted directly when pixel scale is plausible, values are finite, and it lies within reachable hint range; source and match counts are telemetry only. Large target/mount residuals against QHY are no longer mislabeled as an inter-camera axis offset. If the target is outside the frame, the plugin performs bounded segmented centering through N.I.N.A. from the new WCS, then verifies the actual sky response with fresh reported position and a fresh G3 solve.",
            ["Skip（默认）：不运行模板；AutoIfValidElseSkip：模板无效时继续既有长曝光 WCS/N.I.N.A. 居中/小步重解；RequireValid：模板无效时暂停等待处理。"] = "Skip (default): do not run the template. AutoIfValidElseSkip: if invalid, continue with the existing long-exposure WCS / N.I.N.A. centering / small-step re-solve route. RequireValid: pause for intervention when the template is invalid.",
            ["UVEX 设备手控：切缝、狭缝灯和 M2 小步进；不要求自动观测全套准入。"] = "UVEX device controls: slit selection, slit illumination, and small M2 moves; full automatic-observation admission is not required.",

            // Static binding formats are localized by the attached behavior too.
            ["暂停原因：{0}"] = "Pause reason: {0}",
            ["控制服务：{0}"] = "Control service: {0}",
            ["绑定 DeviceId：{0}"] = "Bound DeviceId: {0}",
            ["单帧设置：{0}"] = "Single-frame settings: {0}",
            ["错误代码：{0}"] = "Error code: {0}",
            ["质量数值：{0}"] = "Quality metrics: {0}",
            ["建议：{0}"] = "Recommendation: {0}",
            ["失败证据：{0}"] = "Failure evidence: {0}",
            ["最近证据：{0}"] = "Latest evidence: {0}",
            ["代码：{0}"] = "Code: {0}",
            ["数值：{0}"] = "Metrics: {0}",
            ["证据：{0}"] = "Evidence: {0}",
            ["策略：{0}"] = "Policy: {0}",
        };

    internal static IReadOnlyDictionary<string, string> EnglishTranslations => English;

    internal static bool IsChinese(CultureInfo? culture) =>
        string.Equals((culture ?? CultureInfo.CurrentUICulture).TwoLetterISOLanguageName, "zh", StringComparison.OrdinalIgnoreCase);

    internal static string Translate(string? source, CultureInfo? culture = null)
    {
        if (string.IsNullOrEmpty(source) || IsChinese(culture))
        {
            return source ?? string.Empty;
        }

        if (English.TryGetValue(source, out var translation))
        {
            return translation;
        }

        // Machine identifiers and already-English product terminology pass
        // through unchanged. An unmapped Chinese literal is made conspicuous in
        // English instead of silently leaking a mixed-language sentence.
        return ContainsCjk().IsMatch(source)
            ? "Additional operator information (translation unavailable)."
            : source;
    }

    [GeneratedRegex("[\\u3400-\\u9fff]", RegexOptions.CultureInvariant)]
    private static partial Regex ContainsCjk();
}
